### ISSUE TITLE
MQTT is not using TLS

### ISSUE THREAD

**Issue by TommyTran732** [h-mdm/hmdm-server#101]
I see that mqtt is mqtt:// and not ssl://...

Can you update the source code to use TLS for mqtt?

**Comment by h-mdm** [comment]
We encountered issues when attempting to use TLS for MQTT: a client library (Eclipse Paho) couldn't connect. Therefore we decided to move from unencrypted MQTT to "Long polling" over HTTPS. If you concern about the connection security, please use "HTTP polling" option instead of MQTT, it has been implemented in version 5.27.
