### ISSUE TITLE
IP address problem

### ISSUE THREAD

**Issue by AbdoulMatinou** [h-mdm/hmdm-server#109]
Hi I have some problems with hMDM when my local server changes IP address. I figured that the IP address is stored in the configuration files during installation and that it does not update when it changes. I checked the configuration files as well as those of tomcat but I cannot resolve the problem. I have to do a new installation every time the IP address of my server changes. How to solve the problem? Thanks in advance

**Comment by h-mdm** [comment]
If you change the IP address of the server, you need:
1. Change all entries in /var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml
2. Manually change the server URL on all mobile devices (through the Admin panel, tap and hold the key icon on Headwind MDM desktop)
3. Open the Applications tab, find all entries of URLs with your IP address, click "Edit" and change the IP address
To avoid issues like this in the future, we recommend to use a domain name instead of IP address. In that case, not only you don't need to change the configs, but also you're able to set up HTTPS.
